### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by nirum** [grg2rsr/SeqPeelSort#8]
Would be helpful to have:

- Documentation for the main script `SeqPeelSort.py` (what arguments does it take, where does it save outputs, etc.). Some of this is stated in the example usage section, but would be good to have separate docs as a reference.
- Documentation for the configuration file(s) that are needed.

could just be a separate docs.md file, or another section in the README.

**Comment by grg2rsr** [comment]
I have created a seperate `USAGE.md` that contains a more detailed description of usage. I also moved the description about the benchmarking there, as well as included a description of the parameters of the `config.ini`. Note that a description of the parameters is already in the `example_config.ini`, but this is a bit more expanded.
